version: 2
registries:
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    username: x-access-token
    password: ${{secrets.NPM_TOKEN}}
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 5
    registries:
      - npm-github

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "github-actions"
    assignees:
      - "ecarrizo2"
    commit-message:
      prefix: "chore"
      include: "scope"
