# Configuration for GitHub Release Notes generation

# Specify categories for classifying pull requests
categories:
  - title: 🚀 Features
    labels:
      - feature
      - enhancement
  - title: 🐛 Bug Fixes
    labels:
      - bug
      - fix
  - title: 🧹 Maintenance
    labels:
      - chore
      - refactor
  - title: 🛠️ Other Changes
    labels:
      - ''

# Exclude certain labels from appearing in release notes
exclude-labels:
  - skip-release-notes
  - wip

# Define the template for the release notes
template: |
  ## 🚀 What's New

  ### Changes
  ${{CHANGELOG}}

  ## 🚀 Contributors
  Thanks to everyone who contributed to this release:
  ${{CONTRIBUTORS}}
