name: "Dependabot Auto-Approve and Handle Merge for Minor Bumps"

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  auto-approve-and-merge-queue:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Check Branch Protection Rules for Merge Queue
        id: check_merge_queue
        uses: actions/github-script@v7
        with:
          script: |
            const octokit = github.getOctokit(process.env.GITHUB_TOKEN);

            const { data: protectionRules } = await octokit.repos.getBranchProtection({
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch: 'main'
            });

            const hasMergeQueue = protectionRules.required_pull_request_reviews?.dismiss_stale_reviews ?? false;
            console.log(`Merge queue configured: ${hasMergeQueue}`);
            core.setOutput('result', hasMergeQueue);

      - name: Check Dependabot PR and Approve
        uses: actions/github-script@v7
        with:
          script: |
            const octokit = github.getOctokit(process.env.GITHUB_TOKEN);

            const prNumber = context.payload.pull_request.number;

            const { data: pullRequest } = await octokit.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
            });

            if (pullRequest.user.login !== 'dependabot[bot]') {
              console.log('Not a Dependabot PR. Skipping...');
              return;
            }

            const isDevDependencyChange = pullRequest.title.includes('deps-dev');

            if (!isDevDependencyChange) {
              console.log('PR does not affect devDependencies. Skipping...');
              return;
            }

            const versionRegex = /from (\d+\.\d+\.\d+) to (\d+\.\d+\.\d+)/;
            const match = pullRequest.title.match(versionRegex);

            if (match) {
              const oldVersion = match[1];
              const newVersion = match[2];

              const [oldMajor] = oldVersion.split('.');
              const [newMajor] = newVersion.split('.');

              if (oldMajor !== newMajor) {
                console.log('Major version change detected. Skipping auto-merge...');
                return;
              }
            }

            await octokit.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
              event: 'APPROVE',
              body: 'Auto-approved by workflow for Dependabot PRs affecting devDependencies.',
            });

            const isMergeQueueConfigured = core.getInput('result') === 'true';

            if (isMergeQueueConfigured) {
              await octokit.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                labels: ['merge-queue'],
              });
              console.log('Added to merge queue.');
            } else {
              await octokit.pulls.enableAutoMerge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: prNumber,
                merge_method: 'squash',
              });
              console.log('Auto-merge enabled.');
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
