name: Dependabot Auto-Approve and Handle Merge for Minor Bumps

on:
  pull_request:
    branches: [main, qa]
    types: [opened, synchronize]

jobs:
  auto-approve-and-merge-queue:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Check Dependabot PR and Approve
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          PR_NUMBER="${{ github.event.pull_request.number }}"
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_AUTHOR="${{ github.event.pull_request.user.login }}"

          if [[ "$PR_AUTHOR" != "dependabot[bot]" ]]; then
            echo "Not a Dependabot PR. Skipping..."
            exit 0
          fi

          # Use more precise regex to extract version information
          OLD_VERSION=$(echo "$PR_TITLE" | grep -oP 'from \K\d+\.\d+\.\d+')
          NEW_VERSION=$(echo "$PR_TITLE" | grep -oP 'to \K\d+\.\d+\.\d+')

          # Check for major version change
          if [[ ${OLD_VERSION%%.*} != ${NEW_VERSION%%.*} ]]; then
            echo "Major version change detected. Skipping auto-merge..."
            exit 0
          fi

          # Auto approve the PR
          echo "Approving and merging devDependency PR #$PR_NUMBER..."
          gh pr review $PR_NUMBER --approve --body "Auto-approved by workflow for Dependabot PRs affecting devDependencies."

          # Check merge queue configuration
          MERGE_QUEUE_ENABLED=$(gh api repos/${{ github.repository }}/branches/main/protection --jq '.required_pull_request_reviews.dismiss_stale_reviews')

          if [[ "$MERGE_QUEUE_ENABLED" == "true" ]]; then
            echo "Adding PR #$PR_NUMBER to the merge queue..."
            gh pr merge $PR_NUMBER --merge --auto --queue
          else
            echo "Merge queue not enabled. Enabling auto-merge instead."
            gh pr merge $PR_NUMBER --squash --auto
          fi


