name: 'PR Verification'

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    working-directory: ./

jobs:
  format:
    runs-on: ubuntu-latest
    name: PR Verification
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Lint Code
        run: npm run lint

      - name: Run Prettier and check style.
        run: npm run prettier:check

      - name: Run tests
        run: npm run test:cov
