name: Release on Merge to Main

on:
  push:
    branches:
      - main  # Trigger only on merges to the main branch

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Allow creating releases and tagging

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure all tags and commits are fetched

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install Conventional Changelog Angular and Tools
        run: |
          npm install --save-dev conventional-changelog-angular
          npm install --save-dev conventional-recommended-bump
          npm install --save-dev conventional-changelog-cli
          npm install --save-dev semver

      - name: Determine new version
        id: version
        run: |
          # Fetch all tags to ensure git describe works
          git fetch --tags

          # Get the current version from the last Git tag (v1.2.3)
          current_version=$(git describe --tags --abbrev=0 || echo "v0.0.0")

          # Strip the "v" prefix if present
          current_version=${current_version#v}

          # Run the version bump tool with the Angular preset
          bump_type=$(npx conventional-recommended-bump -p conventional-changelog-angular)

          # Use npm's semver tool to calculate the new version based on the bump type
          new_version=$(npx semver "$current_version" -i "$bump_type")

          # Set the new version as an output
          echo "new_version=$new_version" >> $GITHUB_ENV
          echo "::set-output name=new_version::$new_version"

      - name: Generate release notes using GitHub API
        id: changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          release_notes=$(gh api -X POST \
            -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository }}/releases/generate-notes \
            -f tag_name="v${{ env.new_version }}" \
            -f target_commitish="main" \
            -f previous_tag_name="$(git describe --tags --abbrev=0 || echo "")" \
            | jq -r '.body')

          # Set release notes as an output
          echo "release_notes=$release_notes" >> $GITHUB_ENV
          echo "::set-output name=release_notes::$release_notes"

      - name: Create GitHub release
        uses: actions/create-release@v1
        with:
          tag_name: "v${{ env.new_version }}"
          release_name: "Release v${{ env.new_version }}"
          body: ${{ env.release_notes }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
